databases:
  - name: learningsitedb
    plan: free
    databaseName: learningsite
    user: learningsite

services:
  - type: web
    plan: free
    name: learningsite
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn learning_site.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learningsitedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4